### ISSUE TITLE
coverxygen does not generate output

### ISSUE THREAD

**Issue by ghost** [psycofdj/coverxygen#2]
Hi,

I followed your instructions in the readme file. My problem is that the python module isn't generating any output. When I use 

`python3 -m  coverxygen --xml-dir ./doc/xml --output doc-coverage.info`

the doc-coverage.info file is generated, but it's empty. There isn't any log output or error message, so i have no idea how to fix that problem.

I am developing on Ubuntu 16.04 4.4.0-57-generic x86_64.
The python tool doxy-coverage by Alvaro Lopez Ortega works properly. I hope you have an idea how to fix this issue.

Thanks in advance

**Comment by psycofdj** [comment]
Hi,
I missed the notification for this issue...
Can you tell me which version of coverxygen are you running ?

**Comment by ghost** [comment]
I am using version 1.1.1

**Comment by psycofdj** [comment]
I guess the problem comes from --prefix option.

This option tells converxygen to keep only files that matches given path. Default is ``/``.
Depending how you generated your documentation with doxygen, xml files may contain relative paths, stating with ``./``. If it is the case, every files will be ignored.

In version 1.2.0 I added ``--src-dir`` option which tell coverxygen what is your base directory for relative files found in doxygen's xml files.

With version 1.2.0, and assuming your source base directory is ``<path>``, try the following command :

``python3 -m coverxygen --xml-dir ./doc/xml --src-dir <path> --output doc-coverage.info``

**Comment by ghost** [comment]
Yes this works for me. Thanks for your help.
